@startuml photo-shower

actor User
participant LINEBOT
participant ngrok
participant "Client (TODO)" as Client
participant "Server (Spring Boot)" as Server
database "DB (PostgreSQL)" as DB

== register a image ==

User -> LINEBOT: send a image
LINEBOT -> ngrok: webhook
ngrok -> Server: tunneling
Server -> Server: save a image
Server -> DB: save a image path
activate DB
Server --> ngrok: send a message
ngrok --> LINEBOT
LINEBOT --> User

== show a image ==

User -> Client: start
activate Client
loop every 10 seconds
Client -> Server: GET image-path
Server -> DB: SELECT image-path
DB --> Server
deactivate DB
Server --> Client: image-path
Client --> User: show a image
end
deactivate Client

@enduml